CREATE ROLE 
    spring_user LOGIN
    ENCRYPTED PASSWORD 'pass2017'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;


CREATE DATABASE medis_db 
    WITH OWNER = 'spring_user' 
    ENCODING = 'utf8';
