spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: medis.masa0@gmail.com
    password: unirita2017
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true